### ISSUE TITLE
Integrate Rsyslog for writing logs

### ISSUE THREAD

**Issue by kingsimba** [NavInfoNC/ncserver#1]
There should be some basic infrastructure for writing logs.

**Comment by PowerfulWolf** [comment]
# Asynclog

- Asynclog是基于linux系统服务rsyslog.d和vsyslog实现的异步日志工具。模块引用了[phxrpc](https://github.com/Tencent/phxrpc)框架异步日志工具，并进行了二次封装。
- vsyslog 只进行了日志生产工作，通过domain socket发送给rsyslog.d服务，并由rsyslog.d服务进行分发落地，日志路径限于/var/log。

- [ ] 结构图： [ vsyslog <------> rsyslog.d <------> 日志]

## 使用说明

1. 引用头文件nc_log.h
2. 配置rsyslog.d/$serverName.conf
3. 重启rsyslog.d服务

- 备注

- [ ] 我们提供了服务配置文件生成脚本(~/config/generate_config.py)，可用于参考。

## example

```cpp
#include "nc_log.h"
#include <signal.h>
#include <time.h>
#include <sys/time.h>
#include <stdio>
int main()
{
   _registerUpdateLogLevelSignal();
   Logger::instance().init("example", LOG_ERR);
   struct timeval tvStart, tvEnd;
   struct timezone tzStart, tzEnd;
   gettimeofday(&tvStart, &tzStart);
   while(i<10000)
   {
      ASYNC_LOG_INFO("TEST LOG %d", LOG_INFO);
      i++;
   }
   gettimeofday(&tvEnd, &tzEnd);
   prinf("consume time is: %d ms", (tvEnd.tv_sec - tvStart.tv_sec)*1000 + (tvEnd.tv_usec - tvStart.tv_usec)/1000);
}
```

**Comment by kingsimba** [comment]
Merged #2. Feature is integrated.
