### ISSUE TITLE
Support specifying process number in a config file

### ISSUE THREAD

**Issue by kingsimba** [NavInfoNC/ncserver#15]
Now "ncserverctl" has a command line option --child-count to specify process number.
But it's easy to forget to add the option.

So it's better to have a SERVER_DIR/.ncserver.yaml to define the number of processes.

    processCount: 2

**Comment by kingsimba** [comment]
是不是先把ncserverctl上传了？否则别人怎么用？

**Comment by PowerfulWolf** [comment]
pull request 已提交，ncserverctl 和 yaml文件放在了config目录下。

**Comment by PowerfulWolf** [comment]
文档已添加至readme.rst
